### ISSUE TITLE
作者您好，请教一个问题

### ISSUE THREAD

**Issue by hardgit** [jhflovehqy/flutter_bolg_manage#4]
我刚开始接触Flutter，无意间发现了您写的项目，当我clone下您的工程后，发现一个不错的可持久化保存GetxController状态的Widget基类，我尝试按照您的写法把他剥离出一个demo后，无法正常编译，请问需要做什么特殊处理吗？找了好久，却没有发现问题在哪里，期待您的回复！
![图片](https://user-images.githubusercontent.com/31436497/145785784-4e0ac27b-8a57-400b-ac57-96e2f23dc292.png)
![图片](https://user-images.githubusercontent.com/31436497/145785918-eae214ed-8747-40bf-9ff6-c72a282f0c5d.png)
![图片](https://user-images.githubusercontent.com/31436497/145787844-cc971867-846f-4b19-bc93-6d29b0082f60.png)

**Comment by jhflovehqy** [comment]
你好，这是一个空安全支持性的问题，请检查您的代码在可能为空的情况下是否有加空符号

**Comment by hardgit** [comment]
感谢您的回复，我已锁定问题原因， Get.lazyPut(() => SendController()); 这个没有添加
