### ISSUE TITLE
遇到一个困难，求指导

### ISSUE THREAD

**Issue by hxingever** [jhflovehqy/flutter_bolg_manage#6]
作者你好，刚开始接触flutter，发现一个很好的getx状态管理基类，尝试仿写一遍，但是发现报错，搞了好久还是没找到原因，求指导，期待回复，qq：510965496
同样的tab三项：
![image](https://user-images.githubusercontent.com/9794894/149255838-2d0d8a3e-55f8-49b9-b3f8-88fe2dc59f51.png)
![image](https://user-images.githubusercontent.com/9794894/149255881-b900f6a6-90f4-49a1-a21f-85ff0b5df108.png)
![image](https://user-images.githubusercontent.com/9794894/149255905-cecb2879-606c-4b61-91d0-26be306958f3.png)
![image](https://user-images.githubusercontent.com/9794894/149255926-de2442e5-b1e4-4fe6-9d66-5cdc012b1965.png)
基类完全是按照您的写的，
![image](https://user-images.githubusercontent.com/9794894/149256027-f4068c91-dd1e-45d6-9440-9d900b65d3ae.png)
![image](https://user-images.githubusercontent.com/9794894/149256077-20632166-7bb2-4a65-87f4-7199134aa904.png)
主要是这些图了，但是报错如下
![image](https://user-images.githubusercontent.com/9794894/149256172-9cecb26f-91a1-4dd0-8bf6-5bb36c0b27b3.png)
没找到哪里需要检测空安全，求指导，谢谢

**Comment by jhflovehqy** [comment]
你好，先检查一下是否绑定

**Comment by hxingever** [comment]
问题已解决，就是父级没有binding，put到最顶级就好了，非常感谢！！！
